name: horseandriderscompanion
publish_to: none
version: 0.0.1
description: "Horse & Rider's Companion is a robust equestrian platform designed by Matt French, a seasoned horse trainer from San Diego. This app empowers the equestrian community by providing tools for tracking training progress, accessing curated educational resources, and sharing knowledge among riders and enthusiasts. Features include detailed skill tracking for both riders and horses, a library of community-rated educational content, and opportunities for community contributions and feedback. Whether you're a seasoned equestrian or a newcomer, join our community to enhance your training and connect with fellow horse lovers."

dependencies:

  any_link_preview: ^3.0.2
  authentication_repository:
    path: packages/authentication_repository
  auto_size_text: ^3.0.0
  bloc: ^8.1.0
  cache:
    path: packages/cache
  cached_network_image: ^3.2.3
  cloud_firestore: ^5.1.0
  collection: ^1.18.0
  crypto: ^3.0.3
  database_repository:
    path: packages/database_repository
  equatable: ^2.0.3
  firebase_app_check: ^0.3.0+3
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_core_web: ^2.8.0
  firebase_messaging: ^15.0.3
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.3.1
  flutter_bloc: ^8.1.1
  flutter_inappwebview: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_network_image: ^0.0.8
  flutter_typeahead: ^5.0.1
  form_inputs:
    path: packages/form_inputs
  go_router: ^14.1.1
  google_mobile_ads: ^5.0.0
  google_sign_in: ^6.0.2
  # html: ^0.15.4
  # http: ^1.1.2
  html: ^0.15.4
  http: ^1.2.0
  image_network: ^2.5.4+1
  image_picker: ^1.0.4
  intl: ^0.19.0
  mockito: ^5.4.4
  numberpicker: ^2.1.1
  open_mail_app: ^0.4.5
  photo_view: ^0.15.0
  scrollable_positioned_list: ^0.3.8
  searchfield: ^1.0.1
  shared_preferences: ^2.0.18
  shimmer: ^3.0.0
  showcaseview: ^3.0.0
  super_banners: ^0.0.1
  timeago: ^3.3.0
  universal_html: ^2.2.4
  url_launcher: ^6.1.7
# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  very_good_analysis: ^6.0.0
environment:
  sdk: '>= 3.0.0'
flutter:
  assets:
    - assets/
  fonts:
    - family: HorseAndRiderIcons
      fonts:
        - asset: fonts/HorseAndRiderIcons.ttf
  generate: true
  uses-material-design: true
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/horse_logo.png"
  min_sdk_version: 21
  web:
    generate: true
    image_path: "assets/horse_logo.png"
    background_color: "#596475"
    theme_color: "#596475"

flutter_intl:
  enabled: true
  localizely:
    project_id: ad6c1ed5-485f-4d15-b7e6-371baeda80f3
flutter_native_splash:

  #branding_dark: assets/dart_dark.png
  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
    color: '#FFFFFF'
    # Splash screen background color.
    color_dark: '#242526'
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    image: assets/splash_screen_light.png
    # App icon background color.
    #icon_background_color: "#111111"
    # The branding property allows you to specify an image used as branding in the splash screen.
    #branding: assets/dart.png
    # The image_dark, color_dark, icon_background_color_dark, and branding_dark set values that
    # apply when the device is in dark mode. If they are not specified, the app will use the
    # parameters from above.
    image_dark: assets/splash_screen.png
  color: '#E8E8E8'
  # The branding property allows you to specify an image used as branding in the splash screen.
  # It must be a png file. It is supported for Android, iOS and the Web.  For Android 12,
  # see the Android 12 section below.
  #branding: assets/dart.png
  # To position the branding image at the bottom of the screen you can use bottom, bottomRight,
  # and bottomLeft. The default values is bottom if not specified or specified something else.
  #branding_mode: bottom
  # The color_dark, background_image_dark, image_dark, branding_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove
  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color_dark: '#2E2E2E'
  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.
  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: assets/splash_screen_light.png
  #background_image_dark: "assets/dark-background.png"
  image_dark: assets/splash_screen.png
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
    #icon_background_color_dark: "#eeeeee"
  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  #android: true
  ios: true
  remove_alpha_ios: true
  #web: true
  # Platform specific images can be specified with the following parameters, which will override
  # the respective parameter.  You may specify all, selected, or none of these parameters:
  #color_android: "#42a5f5"
  #color_dark_android: "#042a49"
  #color_ios: "#42a5f5"
  #color_dark_ios: "#042a49"
  #color_web: "#42a5f5"
  #color_dark_web: "#042a49"
  #image_android: assets/splash_image_dark.png
  #image_dark_android: assets/splash-invert-android.png
  #image_ios: assets/splash-ios.png
  #image_dark_ios: assets/splash-invert-ios.png
  #image_web: assets/splash-web.png
  #image_dark_web: assets/splash-invert-web.png
  #background_image_android: "assets/background-android.png"
  #background_image_dark_android: "assets/dark-background-android.png"
  #background_image_ios: "assets/background-ios.png"
  #background_image_dark_ios: "assets/dark-background-ios.png"
  #background_image_web: "assets/background-web.png"
  #background_image_dark_web: "assets/dark-background-web.png"
  #branding_android: assets/brand-android.png
  #branding_dark_android: assets/dart_dark-android.png
  #branding_ios: assets/brand-ios.png
  #branding_dark_ios: assets/dart_dark-ios.png
  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  web_image_mode: contain
uses-material-design: true