name: database_repository
description: Dart package which manages the database domain.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cache:
    path: ../cache
  cloud_firestore: ^6.0.0
  equatable: ^2.0.3
  firebase_auth: ^6.0.1
  firebase_auth_platform_interface: ^8.1.0 
  firebase_core: ^4.0.0
  firebase_core_platform_interface: ^6.0.0
  firebase_remote_config: ^6.0.0
  firebase_storage: ^13.0.0
  flutter:
    sdk: flutter 
  html: ^0.15.0
  http: ^1.1.2  
  image_picker: ^1.0.4
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  plugin_platform_interface: ^2.1.3
  very_good_analysis: ^9.0.0
