name: database_repository
description: Dart package which manages the database domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cache:
    path: ../cache
  cloud_firestore: ^4.0.4
  equatable: ^2.0.3
  firebase_auth: ^4.1.0
  firebase_auth_platform_interface: ^6.11.0 
  firebase_core: ^2.1.1
  firebase_core_platform_interface: ^4.5.1
  firebase_remote_config: ^3.0.12
  firebase_storage: ^11.0.6



  flutter:
    sdk: flutter
 
  html: ^0.15.0
  http: ^1.1.2
  
  image_picker: ^1.0.4

  meta: ^1.7.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.1.3
  very_good_analysis: ^3.1.0
